INSERT INTO SHIPMENTS (CUSTOMER_ID, STATUS) VALUES (1, 'COMPLETED');
INSERT INTO SHIPMENTS (CUSTOMER_ID, STATUS) VALUES (2, 'PENDING');
INSERT INTO SHIPMENTS (CUSTOMER_ID, STATUS) VALUES (3, 'PENDING');
INSERT INTO SHIPMENTS (CUSTOMER_ID, STATUS) VALUES (4, 'CREATED');
INSERT INTO SHIPMENTS (CUSTOMER_ID, STATUS) VALUES (5, 'CREATED');
INSERT INTO SHIPMENTS (CUSTOMER_ID, STATUS) VALUES (6, 'CREATED');
INSERT INTO SHIPMENTS (CUSTOMER_ID, STATUS) VALUES (7, 'CREATED');