CREATE TABLE ORDERS
( ID                                        NUMBER(19)                GENERATED BY DEFAULT AS IDENTITY
, ORDER_ID                                  VARCHAR2(36 CHAR)         NOT NULL
, CUSTOMER_ID                               VARCHAR2(36 CHAR)         NOT NULL
, STATUS                                    VARCHAR2(20 CHAR)         NOT NULL
, CREATED                                   TIMESTAMP(6)              NOT NULL
, MODIFIED                                  TIMESTAMP(6)
, CONSTRAINT ORDERS_ORDER_ID                UNIQUE (ORDER_ID)
, CONSTRAINT ORDERS_PK                      PRIMARY KEY (ID)
);