CREATE TABLE ORDERS
( ID                                        NUMBER(19)                GENERATED BY DEFAULT AS IDENTITY
, CUSTOMER_ID                               NUMBER(19)                NOT NULL
, STATUS                                    VARCHAR2(20 CHAR)         NOT NULL
, CREATED                                   TIMESTAMP(6)              NOT NULL DEFAULT CURRENT_TIMESTAMP
, MODIFIED                                  TIMESTAMP(6)              NOT NULL DEFAULT CURRENT_TIMESTAMP
, CONSTRAINT ORDERS_PK                      PRIMARY KEY (ID)
);