CREATE TABLE PRODUCTS
( ID                                        NUMBER (19)                 GENERATED BY DEFAULT AS IDENTITY
, PRODUCT_ID                                VARCHAR2 (36 CHAR)          NOT NULL
, NAME                                      VARCHAR2 (100 CHAR)         NOT NULL
, DESCRIPTION                               VARCHAR2 (4000 CHAR)
, CREATED                                   TIMESTAMP (6)               NOT NULL
, MODIFIED                                  TIMESTAMP (6)
, CONSTRAINT PRODUCTS_PK                    PRIMARY KEY (ID)
, CONSTRAINT PRODUCTS_PRODUCT_ID            UNIQUE (PRODUCT_ID)
, CONSTRAINT PRODUCTS_NAME_UC               UNIQUE (NAME)
);

CREATE TABLE INVENTORY
( ID                                        NUMBER (19)                 GENERATED BY DEFAULT AS IDENTITY
, PRODUCT_ID                                NUMBER (19)                 NOT NULL
, QUANTITY                                  NUMBER (19)                 NOT NULL
, CREATED                                   TIMESTAMP (6)               NOT NULL
, MODIFIED                                  TIMESTAMP (6)
, CONSTRAINT INVENTORY_PK                   PRIMARY KEY (ID)
, CONSTRAINT INVENTORY_PRODUCT_ID_UC        UNIQUE (PRODUCT_ID)
, CONSTRAINT INVENTORY_PRODUCT_ID_FK        FOREIGN KEY (PRODUCT_ID)    REFERENCES PRODUCTS (ID)
);

CREATE TABLE RESERVATIONS
( ID                                           NUMBER (19)                 GENERATED BY DEFAULT AS IDENTITY
, RESERVATION_ID                               VARCHAR2 (36 CHAR)          NOT NULL
, PRODUCT_ID                                   NUMBER (19)                 NOT NULL
, ORDER_ID                                     VARCHAR2 (36 CHAR)          NOT NULL
, QUANTITY                                     NUMBER (19)                 NOT NULL
, STATUS                                       VARCHAR2 (20 CHAR)          NOT NULL
, CREATED                                      TIMESTAMP (6)               NOT NULL
, MODIFIED                                     TIMESTAMP (6)
, CONSTRAINT RESERVATIONS_PK                   PRIMARY KEY (ID)
, CONSTRAINT RESERVATIONS_PRODUCT_ID_FK        FOREIGN KEY (PRODUCT_ID)  REFERENCES PRODUCTS (ID)
, CONSTRAINT INVENTORY_PRODUCT_ID_ORDER_ID_UC  UNIQUE (PRODUCT_ID, ORDER_ID)
);
