CREATE TABLE PRODUCTS
( ID                                        NUMBER(19)                GENERATED BY DEFAULT AS IDENTITY
, PRODUCT_ID                                VARCHAR2(32 CHAR)         NOT NULL
, NAME                                      VARCHAR2(100 CHAR)        NOT NULL
, DESCRIPTION                               VARCHAR2(4000 CHAR)
, CREATED                                   TIMESTAMP(6)              NOT NULL DEFAULT CURRENT_TIMESTAMP
, CONSTRAINT PRODUCTS_PRODUCT_ID            UNIQUE (PRODUCT_ID)
, CONSTRAINT PRODUCTS_NAME_UC               UNIQUE (NAME)
, CONSTRAINT PRODUCTS_PK                    PRIMARY KEY (ID)
);

CREATE TABLE INVENTORIES
( ID                                        NUMBER(19)                GENERATED BY DEFAULT AS IDENTITY
, PRODUCT_ID                                NUMBER (19)               NOT NULL
, QUANTITY                                  NUMBER (19)               NOT NULL
, MODIFIED                                  TIMESTAMP(6)              NOT NULL DEFAULT CURRENT_TIMESTAMP
, CONSTRAINT INVENTORIES_PK                 PRIMARY KEY (ID)
, CONSTRAINT INVENTORIES_PRODUCT_ID_UC      UNIQUE (PRODUCT_ID)
, CONSTRAINT INVENTORIES_ID_FK              FOREIGN KEY (PRODUCT_ID)  REFERENCES PRODUCTS (ID)
);