CREATE TABLE PRODUCTS
( ID                                        NUMBER(19)                GENERATED BY DEFAULT AS IDENTITY
, NAME                                      VARCHAR2(100 CHAR)        NOT NULL
, QUANTITY                                  NUMBER (19)               NOT NULL
, MODIFIED                                  TIMESTAMP(6)              NOT NULL DEFAULT CURRENT_TIMESTAMP
, CONSTRAINT PRODUCTS_PK                    PRIMARY KEY (ID)
);