INSERT INTO PRODUCTS (NAME, QUANTITY) VALUES ('Product 1', 3);
INSERT INTO PRODUCTS (NAME, QUANTITY) VALUES ('Product 2', 324);
INSERT INTO PRODUCTS (NAME, QUANTITY) VALUES ('Product 3', 45);
INSERT INTO PRODUCTS (NAME, QUANTITY) VALUES ('Product 4', 98457);
INSERT INTO PRODUCTS (NAME, QUANTITY) VALUES ('Product 5', 43);
INSERT INTO PRODUCTS (NAME, QUANTITY) VALUES ('Product 6', 2932);
INSERT INTO PRODUCTS (NAME, QUANTITY) VALUES ('Product 7', 322);