#########################
# ACNTECH Configuration #
#########################
acntech:
  service:
    orders:
      url: ${acntech.service.ordering.api.url}/orders
    items:
      url: ${acntech.service.ordering.api.url}/items
    products:
      url: ${acntech.service.warehouse.api.url}/products
    reservations:
      url: ${acntech.service.warehouse.api.url}/reservations
  security:
    login-page: /oauth2/authorization/token-relay-ui
    failure-url: /login/redirect?error
    logout-success-url: ${acntech.security.oauth2-provider.url}/logout.do?client_id=token-relay-ui&redirect=http://localhost:3000
    whitelisted-paths:
      - /**/security/**
      - /**/client/**
  client:
    config:
      security:
        type: OAUTH2_CLIENT

########################
# SPRING Configuration #
########################
spring:
  application:
    name: oauth2-token-relay-ui-api
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false
  jmx:
    enabled: false
  aop:
    proxy-target-class: true
  security:
    oauth2:
      client:
        registration:
          token-relay-ui:
            provider: uaa
            client-id: token-relay-ui
            client-secret: nzSX99Qg
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
        provider:
          uaa:
            issuer-uri: ${acntech.security.oauth2-provider.url}/oauth/token

# Server
server:
  port: 8000
  servlet:
    context-path: /api
    session:
      cookie:
        name: auth_token
